### ISSUE TITLE
Compiled css files (argon.css and argon.min.css) both contains sass variables

### ISSUE THREAD

**Issue by tewshi** [creativetimofficial/argon-dashboard#11]
.icon-xl + .icon-text
{
    **width: calc(100% - $icon-size-xl - 1);**
}
...
.icon-lg + .icon-text
{
    **width: calc(100% - $icon-size-lg - 1);**
}
...
.icon-sm + .icon-text
{
    **width: calc(100% - $icon-size-sm - 1);**
}

**Comment by adriaanzon** [comment]
I was getting an error about this:
>     JisonLexerError: Lexical error on line 1: Unrecognized text.
>
>       Erroneous area:
>     1: 100% - $icon-size-xl - 1

I solved it locally by wrapping the variables in [_icons.scss](https://github.com/creativetimofficial/argon-dashboard/blob/master/assets/scss/core/icons/_icon.scss) with `${}`:

```diff
@@ -28,7 +28,7 @@
        }

     + .icon-text {
-       width: calc(100% - $icon-size-xl - 1);
+       width: calc(100% - #{$icon-size-xl} - 1);
     }
 }

@@ -44,7 +44,7 @@
        }

     + .icon-text {
-       width: calc(100% - $icon-size-lg - 1);
+       width: calc(100% - #{$icon-size-lg} - 1);
     }
 }

@@ -60,6 +60,6 @@
        }

     + .icon-text {
-       width: calc(100% - $icon-size-sm - 1);
+       width: calc(100% - #{$icon-size-sm} - 1);
     }
 }
```

**Comment by JIAZHEN** [comment]
Same here. Any solution?

**Comment by cmutagorama** [comment]
Thank you @adriaanzon, I managed to overcome the error by using your method!

**Comment by rarestoma** [comment]
Hi, 

We fixed it in our last update.

Thank you,
Rares
