### ISSUE TITLE
Nested `collapse`s in navbar

### ISSUE THREAD

**Issue by mokhosh** [creativetimofficial/argon-dashboard#13]
I have a `collapse` item inside my navbar and when I tap on the link to see the nested links, the whole navbar closes and opens again. This doesn't happen when I remove `require('argon')` from my js, and nothing seems to stop working when I remove it.

This makes me wonder, should I have even included the js file in the first place?

**Comment by CoderSquirrel** [comment]
hI @mokhosh checkout issue [#4](https://github.com/creativetimofficial/argon-dashboard/issues/4)
and pr [#6](https://github.com/creativetimofficial/argon-dashboard/pull/6)

**Comment by mokhosh** [comment]
It jumps a little bit, but that's another issue. Thanks.
