### ISSUE TITLE
navbar collapse feature

### ISSUE THREAD

**Issue by sanif** [creativetimofficial/argon-dashboard#21]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
There should be an option for collapsing/expanding side navigation. It should work as normal bootstrap side navigation.

# Current Behavior
Side navigation is fixed and is collapsing only for mobile.
What is the current behavior?

**Comment by rarestoma** [comment]
Hello,

Thnak you for working with our products.

We provide a mini side navigation in our PRO product (https://demos.creative-tim.com/argon-dashboard-pro/pages/dashboards/dashboard.html). Hope it helps.

All the best,
Rares
