### ISSUE TITLE
Missing .map files

### ISSUE THREAD

**Issue by rodfraga** [creativetimofficial/argon-dashboard#23]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed
- [ Yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
.map files must be included

# Current Behavior
.map files are missing for:

/on-screen.umd.min
/bootstrap.bundle.min
/jquery-scrollLock.min.js
/jquery-3.1.1.min.js

What is the current behavior?
I recently purchased the Argon Dashboard Pro / also tested the Argon Free version, and once the template is imported to a Razor Page C# using .NET Core if I open the inspector/dev tools in Chrome or Safari In got several errors about those .map files not found.

# Failure Information (for bugs)

File Not Found

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 : Create your website .NET Core
2. step 2: debug/publish website on .NET Core
3. step 3: Check inspector
4: step 4: Notice not found errors

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iMac
* Operating System: MacOS / Azure
* Browser and Version: Chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

Very soon will be launched the C# version of argon dashboard. Please wait for it so everything you need will be available there.

All the best,
Rares
