### ISSUE TITLE
Change datepicker format to dd/mm/yyyy

### ISSUE THREAD

**Issue by SondayAyoub** [creativetimofficial/argon-dashboard#25]
I want to change the datepicker input to return the date value in this format: dd/mm/yyyy

PS: I'm using the range option!

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

Please check the official documentation of datepicker https://bootstrap-datepicker.readthedocs.io/en/latest/.

All the best,
Rares

**Comment by WilliamWalker** [comment]
I had the same desire. I chose to replace the argon-dashboard class with one of my own, and then use the (modified argon-dashboard.js) function below:
```
var Datepicker = (function() {
      // Variables
      var $datepicker = $('.datepicker-yyyymmdd');

      // Methods
      function init($this) {
        var options = {
          disableTouchKeyboard: true,
          autoclose: true,
          format: "yyyy-mm-dd"
        };
        $this.datepicker(options);
      }

      // Events
      if ($datepicker.length) {
        $datepicker.each(function() {
          init($(this));
        });
      }
    })();
```

**Comment by rarestoma** [comment]
Hi,

I see that now in your js the format is different from dd/mm/yyyy. Did you try with format: 'mm/dd/yyyy'?

All the best,
Rares
