### ISSUE TITLE
[Bug] JavaScript from Argon is not working

### ISSUE THREAD

**Issue by JoakimBrandt** [creativetimofficial/argon-dashboard#26]
### Version
0.1.0

### Reproduction link
https://jsfiddle.net/a6dh28m5/

### Operating System
Linux Ubuntu

### Device
PC

### Browser & Version
Chrome Latest

### Steps to reproduce
1. Download the standard version of Argon Dashboard
2. Try to use any kind of JavaScript components, such as modals, pagination, popovers etc
3. See that none of those works, sadly. :(

### What is expected?
I expected JavaScript objects to behave properly. I expect popovers to pop, modals to modal and paginations to paginate. 

I noticed that Argon Dashboard free does not include many JS-files at all, so I tried to include files from the standard Argon site, but that did not work either..

I just want to be able to use Bootstrap, JQuery etc, but it won't let me.
### What is actually happening?
Buttons and styles work perfectly, just not the JavaScript methods/commands.

---

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

I tried now again and everything is working perfectly.  Take, for example, the dashboard page, erase all the content except the scripts and CSS, add a modal from here(https://demos.creative-tim.com/argon-dashboard/docs/components/modal.html) and it should work.

Please let me know if it helps.

All the best,
Rares

**Comment by JoakimBrandt** [comment]
Hi, 

Thank you for your reply. Okay, I realized I posted on the wrong github page, this was meant for the Argon Vue Dashboard. Terribly sorry.

Deepst regards.
