### ISSUE TITLE
Checkbox without label

### ISSUE THREAD

**Issue by ZeProf2Code** [creativetimofficial/argon-dashboard#28]
### Version
Latest
### Reproduction link
https://www.this.is.not.a.bug
### Operating System
Windows 10
### Device
Computer
### Browser & Version
Chrome, Latest
### Steps to reproduce
Is there a possibility to do a checkbox without a label?
### What is expected?
That I know how to do a checkbox without a label
### What is actually happening?
I don't know how to make a checkbox with a label

---

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Yes, you can remove the text from the label so you will have just the checkbox.

Try this code and see if it works as you like:
```
<div class="custom-control custom-checkbox mb-3">
     <input class="custom-control-input" id="customCheck1" type="checkbox">
     <label class="custom-control-label" for="customCheck1"></label>
</div>
```

I hope it helps.

All the best,
Rares

**Comment by ZeProf2Code** [comment]
Hello, thanks for the reply and no, it doesn't works for me.
![image](https://user-images.githubusercontent.com/32982428/61931340-a460e900-af80-11e9-8e95-46882ed17b62.png)

**Comment by rarestoma** [comment]
Hello,

Can you please give me a codepen link so I can see clearly how I can stylize it?

All the best,
Rares

**Comment by ZeProf2Code** [comment]
Here is is : https://codepen.io/anon/pen/oKYvEw (it's in my php blade file)

**Comment by rarestoma** [comment]
Hi,

Please add this css code:
```
 .custom-checkbox .custom-control-input~.custom-control-label{
    height:20px;
}
```

Please let me know if everything is all right. 

All the best,
Rares

**Comment by ZeProf2Code** [comment]
Thank you! And do you have a way to correctly style dataTables in cards?
Actually, it looks like this : 
![image](https://user-images.githubusercontent.com/32982428/62126641-7953fd80-b2d0-11e9-9730-9257a22e530e.png)

**Comment by rarestoma** [comment]
Hi,

We styled the datatable in our PRO version available here: https://demos.creative-tim.com/argon-dashboard-pro/pages/tables/datatables.html.

All the best,
Rares
