### ISSUE TITLE
[Feature Request] Map

### ISSUE THREAD

**Issue by CreArt16** [creativetimofficial/argon-dashboard#32]
### What is your enhancement?
Hi, how can I change the description of the map where it says 'Argon Dashboard' and customize this?

**Comment by rarestoma** [comment]
Hello @CreArt16,

Thank you for working with our products. 

You can modify and customize the map in the js file, where the map is initialized('function initMap()'). The title for the marker is now 'Hello World' and can be changed in the same function where the marker is initialized, editing the title attribute.

Please let me know if it works.

All the best,
Rares
