### ISSUE TITLE
Fixed Footer on Pro Version

### ISSUE THREAD

**Issue by agusm** [creativetimofficial/argon-dashboard#33]
How to render footer as fixed position?

**Comment by rarestoma** [comment]
Hi @agusm,

Thank you for working with our products. Please try these classes on the footer tag: "footer pt-0 position-sticky bottom-0". It should work now.

All the best,
Rares

**Comment by Pixelairport** [comment]
<footer class="footer pt-0 position-sticky bottom-0"> make the footer not stick to the bottom :(

**Comment by agusm** [comment]
That's not working

**Comment by rarestoma** [comment]
Hello,

Can you please give me a photo or a jsfiddle link with the code?

Are you using the Free or the PRO version?

Thank you,
Rares

**Comment by Pixelairport** [comment]
not sure why,... now it is working

Am Do., 14. Nov. 2019 um 09:03 Uhr schrieb rarestoma <
notifications@github.com>:
