### ISSUE TITLE
[Bug] Sidebar menu when status is pinned always

### ISSUE THREAD

**Issue by breim** [creativetimofficial/argon-dashboard#38]
### Version
i dont kown
### Reproduction link
https://youtu.be/fpe0CFUjrP4?t=38
### Operating System
MacOS
### Device
MacOS
### Browser & Version
Chrome 79.0.3945.117
### Steps to reproduce
When the user navigates to another page the menu collapses, causing a not very pleasant navigation. Ideally it should be fixed when Cookies.get ('sidenav-state') == 'pined' is true

Here in the company we use the Vue version and it does not present this problem. In the version of this bug we are using Argon Dashboard PRO (HTML only)

Check the example: https://youtu.be/fpe0CFUjrP4?t=38

### What is expected?
Menu stay open

Check the example: https://youtu.be/fpe0CFUjrP4?t=38
### What is actually happening?
Meu load closed and change status to open, causing a dumb animation.

Check the example: https://youtu.be/fpe0CFUjrP4?t=38

---

**Comment by rarestoma** [comment]
Hi @breim,

Thank you for working with our products.

A good solution would be to add static 'g-sidenav-show g-sidenav-pinned' on every page.

Please let me know if it works.

All the best,
Rares

**Comment by breim** [comment]
Ok buddy :)
