### ISSUE TITLE
Navbar with delay - 3 clicks to close

### ISSUE THREAD

**Issue by carlospetrucio** [creativetimofficial/argon-dashboard#39]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

Navigating to the right when in mobile or responsive mode does not close quickly, I click once on the icon and the menu opens, after that it is necessary at least 3 clicks for the menu to return to the initial state.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 - Access in responsive mode
2. step 2 - Click on the icon to open the menu
3. step 3 - At this moment when clicking only once to close, following the same to open it does not close the menu, being necessary to repeat the action 3 times...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome - Updated

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by carlospetrucio** [comment]
Yes the navbar opens but does not close on any mobile, and when it closes it takes 3 clicks.

**Comment by rarestoma** [comment]
Hi @carlospetrucio,

Thank you for working with our products and for pointing us this issue.

Please remove the following lines of code from the argon.js:

`case 'sidenav-pin':`
               ` pinSidenav();`
           ` break;`
           ` case 'sidenav-unpin':`
                `unpinSidenav();`
           ` break;`

You find it in switch(action) function from line 94 to line 100.

Please let me know if everything works properly now.

All the best,
Rares

**Comment by carlospetrucio** [comment]
Ok, thanks.

**Comment by carlospetrucio** [comment]
Após acessar meu arquivo "argon.js" e remover 
case 'sidenav-pin':
pinSidenav();
break;
case 'sidenav-unpin':
unpinSidenav();
break;
-
Agora resolvido, sem delay ao abrir menu.
