### ISSUE TITLE
sidebar component with subitem

### ISSUE THREAD

**Issue by Phathdt** [creativetimofficial/argon-dashboard#4]
do we have example sidebar component with subitem can toggle active ?

**Comment by amousavii** [comment]
You can use this code

> 

                  <a class="nav-link" href="#homesubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="ni ni-planet text-blue"></i> Icons </a>
                        <ul class="collapse list-unstyled" id="homesubmenu" >
                            <li class="nav-item">
                                <a  class="nav-link" href="#">
                                    <i class="ni ni-planet text-blue"></i> Icons </a>
                                </a>
                            </li>
                        </ul>
Change the icons as desired,

>

**Comment by CoderSquirrel** [comment]
I'm adding apull request with a propose to add a feature like style tomultilevel
the code pen
https://codepen.io/CoderSquirrel/pen/qJMPqM

**Comment by rarestoma** [comment]
Hello,

Thank you for your interest in our products and sorry for the late respone.

We provide a multi level menu in our pro version(https://demos.creative-tim.com/argon-dashboard-pro/pages/tables/datatables.html) in  components -> multi level.

Hope it helps.

All the best,
Rares
