### ISSUE TITLE
Actions menu isn't properly displayed

### ISSUE THREAD

**Issue by AlexZaytsav** [creativetimofficial/argon-dashboard#40]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version: I use version 1.1 but tested this behaviour at your demo page(I assume that it's running the latest version) and it happens there too.
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Actions menu is on top of the footer.

# Current Behavior

Actions menu is overlapped by tables footer If there is only one row in the table.

![Screenshot 2020-02-21 at 15 30 33](https://user-images.githubusercontent.com/1477925/75173368-9ffdd980-56e3-11ea-83ef-508a89ef204b.png)

## Steps to Reproduce

1. Render table with only 1 row
2. Click Actions icon ('.btn.btn-sm.btn-icon-only.text-light')

**Comment by rarestoma** [comment]
Hi @AlexZaytsav,

Thank you for working with our products.

To make the dropdown visible in the table please add 'overflow-visible' on 'table-responsive''s div.

`<div class="table-responsive overflow-visible">`
`<table class="...">`
`...`
`</table>`
`</div>`

Please let me know if it works properly now.

All the best,
Rares

**Comment by AlexZaytsav** [comment]
Hi @rarestoma,

Thank you for the suggestion. It helped!

Thank you for building your great product!

Thanks,
Alex.

**Comment by rarestoma** [comment]
Hi @AlexZaytsav,

I am happy to hear that now it is working.

Please let me know if you need help with anything.

All the best,
Rares
