### ISSUE TITLE
Missing files in gulp build

### ISSUE THREAD

**Issue by pauldbentley** [creativetimofficial/argon-dashboard#43]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Running gulp build should complete with no errors

# Current Behavior

Running gulp build gives errors.

# Failure Information (for bugs)

[09:37:19] 'concat:js' errored after 16 ms
[09:37:19] Error: File not found with singular glob: /assets/js/components/license.js (if this was purposeful, use `allowEmpty` option)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run gulp build

**Comment by rarestoma** [comment]
Hi @pauldbentley,

Thank you for working with our products and for pointing us this issue.

Please modify the gulpfile.js with:

1. in `gulp.task('minify:js'... )` replace `'/assets/js/argon.js' ` with `'assets/js/argon.js'`
2. please remove from `gulp.task('concat:js'...` the first 2 files( `paths.src.base + '/assets/js/components/license.js'` and `paths.src.base + '/assets/js/components/layout.js'`)

Please let me know if it works.

All the best,
Rares

**Comment by pauldbentley** [comment]
Thanks - that fixes the issues.  I've submitted a PR if you accept them.
