### ISSUE TITLE
NPM version publishing (1.2.0)

### ISSUE THREAD

**Issue by Swizz** [creativetimofficial/argon-dashboard#44]
Hi there,

Argon Dashboard 1.2.0 looks really promising, any clue about the when you will release/publish the latest 1.2.0 version on the npm packages store ?

We use the npm packaging to handle all of our dependencies, Argon included. 

Cheer,

**Comment by rarestoma** [comment]
Hi @Swizz,

Thank you for working with our products.

We just added the latest version of npm.

Please let me knwo if you need help with anything else.

All the best,
Rares

**Comment by Swizz** [comment]
Like a charm ! 

Thank you a lot for all your work.
