### ISSUE TITLE
Not working on Laravel 7.0

### ISSUE THREAD

**Issue by sboal94** [creativetimofficial/argon-dashboard#45]
Please update your template, I am going crazy after spending 4 hours trying to install ArgonDashboard on my Laravel 7.0 project!!!
The project works on version5.5 and install ok, in 6.2 install ok but in Laravel 7.0 it is not working!!

Please update for Laravel 7.0 or say this don´t work on this version.

**Comment by rarestoma** [comment]
Hi @chalangui,

Thank you for working with our products.

Did you try working with our Laravel Argon Dashboard https://www.creative-tim.com/product/argon-dashboard-laravel?

Thank you,
Rares

**Comment by mr-observer** [comment]
And problems with compiling SASS assets using Laravel Mix (Laravel 8).

`ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100% - $icon-size-lg - 1
^.........^`

**Comment by rarestoma** [comment]
Hi @mr-observer,

Thank you for working with our products.

Please change `100%-$icon-size-lg - 1` to `100%-#{$icon-size-lg}-1`.

Please let me know if it works.

Thank you,
Rares

**Comment by mr-observer** [comment]
Hello @rarestoma 

Additionally, images for the calendar do not exist in the archive and in the NPM package, so the build fails. It will be ideal if you can fix it to use plain NPM over placing all the dependencies in the project folder.

Thanks for the help.

**Comment by rarestoma** [comment]
Hi @mr-observer,

Are you using the PRO version of Argon Dashboard?

Thank you,
Rares
