### ISSUE TITLE
footer moves up with the content

### ISSUE THREAD

**Issue by attilatoth86** [creativetimofficial/argon-dashboard#8]
If the content is not long enough the footer moves up, potentially into the middle of the page. Is there a way to keep it in the bottom even if the site content does not fill up the available space?

![screenshot 2018-11-06 at 22 06 42](https://user-images.githubusercontent.com/10468021/48093736-7bd96900-e210-11e8-804f-4663d1591719.png)

**Comment by rarestoma** [comment]
Hello,

Sorry for the late response.

Please do the following changes:
In the css files add these lines:
.main-content{
 min-height:100vh;
}
.footer{
    position: absolute;
    width: 95%;
    bottom: 0;
    height: 0%;
}

Please let me know if I can help you with anything else.

All the best,
Rares

**Comment by bartek-dec** [comment]
Hello 
The above solution doesn't work when the page is full of content. In that case, the footer covers content. Is there a way to keep footer at the bottom even if the site content does not fill up the available space (as asked by attilatoth86) and keep footer below the content when the page is filled up?

![Screenshot](https://user-images.githubusercontent.com/26393246/68937155-d26a7300-0793-11ea-9c63-c50d32f6ec58.png)

**Comment by mudenho** [comment]
`.main-content{
        min-height:100vh;
    }
    .footer{
        position: absolute;
        width: 95%;
        bottom: 10px;
        height: 0;
    }
`
Add padding to the dive before the footer
`padding-bottom: 20px`

**Comment by hridoy100** [comment]
> Hello,
> 
> Sorry for the late response.
> 
> Please do the following changes:
> In the css files add these lines:
> .main-content{
> min-height:100vh;
> }
> .footer{
> position: absolute;
> width: 95%;
> bottom: 0;
> height: 0%;
> }
> 
> Please let me know if I can help you with anything else.
> 
> All the best,
> Rares

This solution doesn't work.  Please provide a working solution.

**Comment by dan-whitehouse** [comment]
The only thing I'd suggest differently is setting the width to 97%, it seems to line up with the end of the container. Also, I used .pb-4 on the div before my footer.

    <style>
        .main-content{ min-height:100vh; }
        .footer{ position: absolute; width: 97%; bottom: 10px; height: 0; }
    </style>


    <div class="container-fluid mt--6">
        <div class="row pb-4"></div>
        <footer class="footer"></footer>
    </div>

**Comment by attilatoth86** [comment]
thank you all, it worked.
